import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_DIR = ROOT / "en"

# Complete dictionary of deep string replacements for visible UI text
REPLACEMENTS = {
    # Common UI
    "Descargar Reporte en PDF": "Download PDF Report",
    "Descargar Reporte": "Download Report",
    "Descargar PDF": "Download PDF",
    "Descargar CSV": "Download CSV",
    "Descargar HTML": "Download HTML",
    "Descargar PNG": "Download PNG",
    "Descargar": "Download",
    "Guardar en historial": "Save to History",
    "Guardar cliente": "Save Client",
    "Guardar cotización": "Save Quote",
    "Guardar Cotización": "Save Quote",
    "Guardar": "Save",
    "Limpiar todo": "Clear All",
    "Limpiar": "Clear",
    "Copiar": "Copy",
    "Copiar HTML": "Copy HTML",
    "Copiar enlace": "Copy Link",
    "Clic para copiar": "Click to copy",
    "Previsualización": "Preview",
    "Vista previa": "Preview",
    "Historial": "History",
    "Configuración": "Settings",
    "Copia de Seguridad": "Data Backup",
    "Exportar Base de Datos": "Export Database",
    "Importar Base de Datos": "Import Database",
    "Volver al directorio": "← Back to Directory",
    "Volver al portal": "← Back to Portal",
    "Volver": "← Back",
    "Todos los departamentos": "All Departments",
    "Todos los proyectos": "All Projects",
    "No data para mostrar": "No data to display",
    "Sin datos": "No data",
    "En progreso": "In Progress",
    "Completado": "Completed",
    "Pendiente": "Pending",
    "Bloqueado": "Blocked",
    "Alta resolución": "High Resolution",
    "Sincronizar en la nube": "Cloud Sync",
    "Datos guardados localmente": "Data saved locally in browser",

    # Analizador de Titulares
    "Puntaje global de atractivo": "Overall Headline Score",
    "Sugerencias en vivo": "Live Recommendations",
    "Escribe un titular arriba para recibir sugerencias en vivo.": "Enter a headline above to get real-time recommendations.",
    "Impacto psicológico global:": "Overall Psychological Impact:",
    "Tono de marca": "Brand Tone",
    "Vista previa en buscadores": "Search Engine Preview",
    "Vista previa en redes sociales": "Social Media Preview",
    "Comparación A/B": "A/B Comparison",

    # Auditor SEO
    "Suite de análisis de metaetiquetas": "Meta Tags & SEO Audit Suite",
    "Analiza tu SEO On-Page como los": "Audit Your On-Page SEO Like the",
    "Extrae metaetiquetas, previsualiza en buscadores y redes, compara competidores, registra la evolución y exporta informes completos.": "Extract meta tags, preview search and social snippets, benchmark competitors, track progress, and export comprehensive reports.",
    "Extracción automática": "Automated Extraction",
    "Puntuación global": "Overall Health Score",
    "Calculada a partir de los criterios cumplidos en tiempo real": "Calculated from fulfilled criteria in real time",
    "Puntuación General": "Overall Score",
    "Crítico": "Critical",
    "Se resalta en la vista previa y en las comprobaciones.": "Highlighted in previews and validation checks.",
    "Título meta": "Meta Title",
    "Óptimo: 30–60 caracteres.": "Optimal: 30–60 characters.",
    "Óptimo: 70–160 caracteres.": "Optimal: 70–160 characters.",
    "Vista previa en Google": "Google Search Preview",
    "Título de tu página — vista previa": "Your Page Title — Search Preview",
    "Aquí aparecerá tu meta descripción. Escribe una descripción atractiva para mejorar el CTR en los resultados de búsqueda.": "Your meta description will appear here. Write a compelling description to boost click-through rates in search results.",
    "Título de tu enlace compartido": "Shared Link Title",
    "Descripción que aparecerá cuando compartas este enlace en redes sociales.": "Description displayed when sharing this link on social media networks.",
    "Metatítulo entre 30 y 60 caracteres": "Meta title between 30 and 60 characters",
    "Existe un encabezado H1": "Single H1 heading is present",
    "La palabra clave aparece en el Meta Título": "Keyword appears in Meta Title",
    "La palabra clave aparece en la Meta Descripción": "Keyword appears in Meta Description",
    "La palabra clave aparece en el H1": "Keyword appears in H1 heading",
    "Mejorar con IA": "Optimize with AI",
    "Lista de tareas accionable para tu programador": "Actionable Checklist for Developers",
    "0 de 14 tareas completadas": "0 of 14 tasks completed",
    "Ajustar la longitud del Meta Título": "Adjust Meta Title Length",
    "Reescribe el título para que tenga entre 30 y 60 caracteres, incluyendo la palabra clave al inicio.": "Rewrite the title to 30–60 characters, placing your primary keyword near the beginning.",
    "Ajustar la longitud de la Meta Descripción": "Adjust Meta Description Length",
    "Inserte una única etiqueta <h1> descriptiva que resume el contenido de la página.": "Insert a single descriptive <h1> heading that summarizes the core page topic.",
    "Selecciona la palabra clave principal por la que quieres posicionar esta página.": "Select the primary target keyword you want this page to rank for.",
    "Incluye una meta descripción para mejorar la comprensión del contenido en resultados.": "Include a meta description to improve clickability in search engine results.",
    "Analizar el contenido textual": "Analyze Body Text Content",
    "Pegue el contenido del artículo para evaluar la densidad de palabras y legibilidad.": "Paste the article body text to analyze keyword density and readability.",
    "Ampliar la extensión del contenido": "Expand Content Length",
    "Desarrolla el contenido hasta al menos 300 palabras para mejorar la relevancia temática.": "Expand content to at least 300 words to enhance topical depth and relevance.",

    # Descuentos y Promociones
    "Simulador de rentabilidad": "Profitability Simulator",
    "Calculadora de Descuentos": "Discount & Promotions Calculator",
    "Evalúa si tu campaña de descuento sigue siendo rentable antes de lanzarla. Compara el margen normal contra el margen con promoción y recibe un veredicto claro.": "Evaluate whether your discount campaign remains profitable before launch. Compare regular margin against promotional margin and get a clear commercial verdict.",
    "% de Descuento": "Discount %",
    "Costo por unidad": "Unit Cost",
    "Precio normal": "Regular Price",
    "Margen mínimo aceptable": "Minimum Acceptable Margin",
    "Punto de Equilibrio de la Campaña": "Campaign Break-Even Point",
    "¿Cuántas unidades extra necesitas vender con el descuento solo para igualar la ganancia que tendrías un precio normal?": "How many additional units must you sell at discount just to match your regular profit?",
    "Volumen normal de ventas (unidades)": "Regular Sales Volume (units)",
    "Ingresa costo y precio normal arriba para calcular el punto de equilibrio.": "Enter cost and regular price above to calculate break-even point.",
    "Estrategia de Combos (Bundling)": "Bundling Strategy (Combo Kits)",
    "Combina hasta 3 productos y descubre el descuento máximo seguro para venderlos juntos como un Kit sin entrar en pérdidas.": "Combine up to 3 products and discover the maximum safe bundle discount without operating at a loss.",
    "Ingresa costo y precio de al menos 2 productos (con precio mayor al costo) para generar la estrategia de combo.": "Enter cost and price for at least 2 products (with price > cost) to generate bundling strategy.",
    "Valor de vida del cliente (CLV)": "Customer Lifetime Value (CLV)",
    "¿Vale la pena perder margen hoy con una oferta agresiva? Calcula cuánta ganancia neta deja el cliente en 12 meses frente a la inversión inicial de la promoción.": "Is it worth sacrificing margin today for an aggressive offer? Calculate net customer profit over 12 months vs initial promotional acquisition cost.",
    "Frecuencia de compra anual": "Annual Purchase Frequency",
    "Retención esperada (%)": "Expected Retention Rate (%)",
    "Ingresa costo y precio normal arriba para estimar el valor del cliente.": "Enter cost and regular price above to estimate customer lifetime value.",
    "Textos listos para publicar, generados con los precios reales de tu simulación. Cópialos con un clic.": "Ready-to-publish sales copy generated from your real simulated prices. Copy with one click.",
    "Ingresa costo y precio normal arriba para generar los textos.": "Enter cost and regular price above to generate promotional copy.",
    "Añade urgencia con un temporizador configurable y exporta el bloque de la promoción como HTML puro para tu tienda.": "Add urgency with a countdown timer and export promotional embed as pure HTML for your storefront.",
    "Ingresa costo y precio normal arriba para activar la campaña flash.": "Enter cost and regular price above to activate flash campaign.",

    # Flete y Envío Local
    "Cotización de despacho para comercios pequeños": "Shipping & Freight Quotes for Small Businesses",
    "Planifica y cotiza tus despachos en segundos": "Plan and Quote Deliveries in Seconds",
    "Ingresa el paquete, deja que el sistema sugiera el vehículo, arma una ruta de hasta 5 paradas y compara precios Estándar vs Express con descuento multiparada.": "Enter package specs, let the system suggest a vehicle, plan up to 5 route stops, and compare Standard vs Express delivery pricing with multi-stop discounts.",
    "Zona más usada": "Most Popular Zone",
    "Base tarifa estándar": "Standard Base Tariff",
    "Datos del paquete": "Package Specifications",
    "Vehículo sugerido": "Suggested Vehicle",
    "Paradas de la ruta": "Route Stopovers",
    "Selecciona una parada y toca su zona de destino en el mapa.": "Select a stopover and click its destination zone on the map.",
    "Parada activa en": "Active stop in",
    "Aún no hay cotización": "No Quote Generated Yet",
    "Completa las medidas y el peso del paquete para ver la ruta y la comparativa de precios.": "Complete package dimensions and weight to view route calculations and price comparisons.",
    "Historial de cotizaciones": "Quote History",
    'Todavía no has guardado cotizaciones. Usa "Guardar cotización" para tenerlas a mano aquí.': 'No quotes saved yet. Click "Save Quote" to store them here.',
    "Precios referenciales con fines demostrativos. Local Shipping & Freight Calculator.": "Demonstrative benchmark pricing. Local Shipping & Freight Calculator.",
    "Dirección parada 1": "Stop 1 delivery address",

    # Precios e Impuestos
    "Suite de precios profesional": "Professional Pricing Suite",
    "Datos del producto": "Product Data",
    "Costo del producto": "Product Cost",
    "Margen de ganancia deseado": "Target Net Profit Margin",
    "Porcentaje neto sobre el precio de venta.": "Net percentage based on selling price.",
    "Impuesto aplicable (IGV/IVA)": "Sales Tax / GST Rate",
    "Editable. Por defecto 18%.": "Editable (e.g. 10% GST or state tax).",
    "Precio de venta final": "Final Customer Retail Price",
    "Incluye tu ganancia y el impuesto a pagar.": "Includes profit margin and applicable sales tax.",
    "Ganancia neta": "Net Profit",
    "Todos los cálculos se actualizan en tiempo real. El historial se guarda en este navegador.": "All calculations update in real time. History is stored locally in this browser.",

    # Préstamos y Amortizaciones
    "Sistema francés · Abonos anticipados · Periodo de gracia · Comparador": "French Amortization · Prepayments · Grace Periods · Benchmark",
    "Configura tu crédito": "Configure Your Loan",
    "Tasa de interés anual": "Annual Interest Rate (APR %)",
    "Periodo de gracia": "Grace Period",
    "Principalización": "Capitalization",
    "Guardar A": "Save Scenario A",
    "Guardar B": "Save Scenario B",
    "Guarde la configuración actual como A o B para compararlas.": "Save current configuration as Scenario A or B to compare.",
    "Perfilador de capacidad de pago": "Repayment Capacity Profiler",
    "Ingresa tus datos para evaluar el riesgo.": "Input financial data to assess risk tolerance.",
    "Evolución: capital vs. intereses": "Evolution: Principal vs Interest",
    "Comparar escenarios": "Compare Scenarios",

    # Sobrecostos Laborales
    "Ley Laboral · Perú": "Labor Cost & Payroll Burden Model",
    "Dashboard de Simulación de Planillas": "Payroll & Labor Cost Simulation Dashboard",
    "Simula el costo real de tu equipo con proyección mensual o anual.": "Simulate true employer costs of your team with monthly and annual projections.",
    "Costo Total Empleador": "Total Employer Labor Cost",
    "Provisión total": "Total Provisions & Benefits",
    "Costo promedio por empleado:": "Average cost per employee:",
    "Distribución del costo total": "Total Cost Distribution",
    "Composición del Costo Total Empleador": "Breakdown of Total Employer Cost",
    "Costo por departamento": "Cost by Department",
    "Comparativo del Costo Total Empleador por área": "Total Employer Cost Comparison by Department",
    "Tipo de Seguro": "Health Insurance Type",
    "Tipo de Pensión": "Pension / Superannuation Plan",
    "Asignación familiar": "Family Allowance / Dependent Support",
    "No hay empleados para mostrar": "No employees to display",
    "Agrega un empleado, ajusta el filtro o importa un archivo CSV.": "Add an employee, adjust filters, or import a CSV file.",
    "Cálculos referenciales según la legislación laboral peruana (RMV, UIT y tramos de renta). No constituye asesoría legal.": "Simulated calculations for budgeting purposes. Does not constitute formal legal or tax advice.",

    # Campañas Avanzado
    "Agregar campaña": "Add Campaign",
    "Nombre de la campaña": "Campaign Name",
    "Margen de Beneficio": "Profit Margin",
    "Agregar a la comparativa": "Add to Comparison",
    "Aún no has agregado campañas. Complete el formulario para comenzar a comparar.": "No campaigns added yet. Complete the form to start benchmarking.",

    # Consola Campañas
    "Consola de campañas": "Campaign Console",
    "Generador de Códigos": "Campaign URL Builder",
    "Etiqueta URLs con nomenclatura segura, genera QR, acorta enlaces, organiza campañas y proyecta su embudo de conversión.": "Tag URLs with safe tracking parameters, generate QR codes, organize campaigns, and project your conversion funnel.",
    "Generador único": "Single URL Builder",
    "Generador en lote": "Batch URL Builder",
    "Etiquetado en bloque": "Bulk Tagging",
    "Proyección": "Funnel Projection",
    "Plantillas rápidas": "Quick Presets",
    "Anuncios de Facebook": "Facebook Ads",
    "Anuncios de Google": "Google Ads",
    "Correo electrónico": "Email Newsletter",
    "Los parámetros se formatean en vivo (minúsculas, sin acentos ni espacios) para no romper Google Analytics.": "Parameters are formatted live (lowercase, no accents, no spaces) to safeguard Google Analytics reports.",
    "Salida en vivo": "Live Tracking URL Output",
    "Introduce una Landing Page URL para generar el enlace rastreable…": "Enter a landing page destination URL to generate a tracked link...",
    "Código QR": "QR Code",
    "Alta resolución (1024px), listo para material impreso y vallas.": "High resolution (1024px), ready for print collateral and billboards.",
    "Enlace corto de demostración para mantener limpios tus posts en redes.": "Demo short link to keep social publications clean.",
    "Panel de campañas": "Campaign Management Deck",
    "Crea tu primera carpeta de campaña para agrupar tus enlaces UTM.": "Create your first campaign folder to organize your UTM links.",
    "UTM Builder · datos guardados localmente en tu navegador": "UTM Builder · Data stored locally in your browser",

    # WebP Forge
    "Convierte imágenes a": "Convert Images to",
    "Arrastra varios JPG o PNG, aplica una marca de agua, ajusta la calidad y descarga todo en WebP —incluso empaquetado en ZIP—. Todo el proceso ocurre en tu navegador.": "Drag multiple JPG or PNG images, add a watermark, adjust compression quality, and download in WebP format — even bundled as a ZIP. Everything happens client-side in your browser.",
    "Empieza soltando tus imágenes aquí": "Start by dropping your images here",
    "Arrastra tus imágenes o haz clic": "Drag images here or click to browse",
    "Sube varias a la vez · JPG o PNG · hasta 5 MB cada una · procesado 100% en tu navegador": "Upload batch files · JPG or PNG · up to 5 MB each · 100% processed in your browser",
    "Seleccionar imágenes": "Select Images",
    "100% en tu navegador": "100% In-Browser Privacy",
    "Tus imágenes nunca salen de tu dispositivo. Conversión con la API Canvas, sin subir a servidores.": "Your images never leave your computer. Converted via HTML5 Canvas without remote server uploads.",
    "Por lotes + ZIP": "Batch Processing + ZIP",
    "Arrastra varias imágenes a la vez, conviértelas todas y descárgalas empaquetadas en un único archivo .zip.": "Drag multiple images at once, convert all of them simultaneously, and download as a single .zip archive.",
    "Superpone tu texto o logo al 50% de opacidad en cada imagen antes de exportarla a WebP.": "Overlays custom text or logo at 50% opacity on every image prior to WebP export.",
    "WebPForge — Optimización de imágenes para la web.": "WebP Forge — Modern Web Image Optimization.",
    "Hecho para amantes del rendimiento web.": "Engineered for web performance enthusiasts.",

    # Facturas Proforma
    "Cliente (busca en frecuentes)": "Client (Search frequent clients)",
    "Detalles del Documento": "Document Details",
    "Conversor de Divisas": "Currency Conversion",
    "Sin conversión": "No conversion (Single currency)",
    "Pago rápido (Código QR)": "Quick Payment (QR Code)",
    "Método de pago": "Payment Method",
    "Diseño de Plantilla": "Template Layout",
    "Tabla de dos colores": "Two-tone alternating table",
    "Marca de agua (semitransparente en el PDF)": "Watermark (Semi-transparent on PDF)",
    "Total de la factura": "Invoice Grand Total",
    "Escribe o selecciona un cliente": "Type or select a client",
    "Concepto (busca en catálogo)": "Line item (Search catalog)",
    "Guardar en catálogo": "Save to catalog",
    "Condiciones de pago, validez de la proforma, etc.": "Payment terms, proforma validity (e.g. 30 days), delivery conditions, etc.",

    # Firma HTML
    "Diseña. Copia. Impresiona.": "Design. Copy. Impress.",
    "Plantilla de inicio rápido": "Quickstart Template",
    "Formal, sólido y directo": "Corporate, clean, and direct",
    "Dinámico, vibrante y llamativo": "Vibrant, modern, and striking",
    "Clásica Vertical": "Classic Vertical Stack",
    "Modo oscuro similar al cliente": "Client Dark Mode Preview",
    "Hola, adjunto la información solicitada. Un cordial saludo,": "Hello, please find the requested information attached. Best regards,",
    "Ana García Ruiz": "Sarah Jenkins",
    "Directora de Marketing": "Head of Marketing",
    "Correo electrónico:": "Email:",
    "Calle Gran Vía 28, Madrid": "120 Market Street, Suite 400",

    # Flujo de Caja
    "todos los movimientos": "All Transactions",
    "por cobrar o pagar": "Pending Inflows / Outflows",
    "Descripción *": "Description *",
    "Categoría": "Category",
    "Operación": "Transaction Type",
    "Cliente o proveedor": "Customer or Vendor",
    "Resumen por categoría": "Summary by Category",
    "Este control es gerencial y no sustituye la contabilidad o declaración tributaria.": "This tool provides managerial cash tracking and does not replace formal accounting or tax filings.",
    "Filtra por tipo o estado y actualiza cada registro.": "Filter by type or status and update each entry directly.",

    # Generador QR
    "Generador en vivo": "Live QR Generator",
    "Enlaces y códigos QR para": "QR Codes & Instant Links for",
    "Crea un enlace directo con tu mensaje predefinido, agrega rastreo UTM y genera un código QR personalizado listo para compartir.": "Create a direct link with pre-filled message, add UTM campaign tracking, and generate a custom QR code ready to distribute.",
    "Longitud óptima": "Optimal Length",
    "Vista previa del mensaje": "Message Preview",
    "en línea": "online",
    "Tu mensaje predefinido aparecerá aquí en tiempo real...": "Your pre-filled message will appear here in real time...",
    "Así verá tu contacto el mensaje al abrir el enlace.": "How your recipient will see the pre-filled message upon opening.",
    "Ingresa un número válido para generar tu código QR": "Enter a valid phone number or URL to generate your QR code",
    "QR Directo · Generador de enlaces y códigos QR para WhatsApp": "Instant QR · QR Code & Link Generator",
    "Código de país": "Country Code",

    # SecuKey Contraseñas
    "Contraseñas seguras para equipos Pyme": "Enterprise-Grade Passwords for SMB Teams",
    "Fuerte · 105 bits de entropía": "Strong · 105 bits of entropy",
    "Tiempo estimado para descifrar": "Estimated Time to Crack",
    "Bajo un ataque de fuerza bruta con GPU offline (10¹¹ intentos/s)": "Under offline GPU brute-force attack (10¹¹ attempts/sec)",
    "Simulación de tipo de atacante": "Threat Actor Simulation",
    "Ataque en línea": "Online Rate-Limited Attack",
    "Fuerza bruta con GPU offline": "Offline GPU Cluster Brute Force",
    "Aplicación de políticas de contraseña inmutables para toda la empresa.": "Enforcing consistent, enterprise-wide password hygiene policies.",
    "Demostración educativa de cómo un autenticador (Google Authenticator, Authy) rota códigos. Activa siempre 2FA en las cuentas críticas de tu Pyme.": "Educational simulation of TOTP rotating security codes (Google Authenticator, Authy). Always enforce 2FA across business systems.",
    "Historial de sesión": "Session History",
    "Las contraseñas generadas aparecerán aquí. Se borrarán al cerrar la pestaña.": "Generated passwords appear here. They are cleared when closing this browser tab.",
    "Cifrado AES-GCM 256 · Procesamiento 100% local · El historial se borra al cerrar la sesión": "AES-GCM 256 · 100% Local Processing · History wiped upon tab close",

    # Contratos de Servicios
    "Documentos legales en minutos": "Professional Legal Contracts in Minutes",
    "Genera contratos de servicios": "Service Agreement Generator",
    "Completa un formulario guiado y observa cómo tu documento toma forma al instante. Descárgalo en PDF, listo para firmar. Explora primero el ejemplo de la derecha para ver la calidad del resultado.": "Complete a guided questionnaire and watch your agreement generate in real time. Download print-ready PDF contracts ready for signing.",
    "Previsualización A4 en tiempo real mientras escribes": "Real-time Live Document Preview as You Type",
    "Plantillas de Contrato de Servicios y Acuerdo NDA": "Master Service Agreement (MSA) & NDA Templates",
    "Firma digital dibujada a mano, incrustada en el PDF": "Hand-drawn digital signature embedded into PDF",
    "Exportación profesional a PDF con un solo clic": "One-click professional PDF export",
    "Ejemplo de resultado · Formato A4": "Sample Output · Standard Letter / A4",
    "Contrato de Prestación de Servicios": "Professional Services Agreement",
    "EL CONTRATISTA": "THE SERVICE PROVIDER",
    "EL CLIENTE": "THE CLIENT",
    "Cláusula Primera: Objeto del contrato": "Section 1: Scope of Services",
    "EL CONTRATISTA se obliga a prestar a favor de EL CLIENTE los siguientes servicios:": "The Service Provider agrees to perform for the Client the following services:",
    "Diseño e implementación de la identidad visual de marca, incluyendo logotipo, manual de estilo y un paquete de plantillas para redes sociales.": "Design and delivery of brand identity assets, including corporate logo, visual style guide, and digital marketing templates.",
    "Cláusula Segunda: Contraprestación": "Section 2: Consideration & Payment Terms",
    "Como contraprestación por los servicios descritos, EL CLIENTE pagará a EL CONTRATISTA la suma total de": "In consideration of the services rendered, the Client shall pay the Service Provider the total sum of",
    ". La forma de pago acordada es la siguiente:": ". The agreed payment schedule is as follows:",
    "50% al inicio del proyecto y 50% contra la entrega final.": "50% upon contract execution and 50% upon final delivery.",
    "Cláusula Tercera: Plazo de entrega": "Section 3: Project Timeline & Delivery Date",
    "EL CONTRATISTA se compromete a entregar los servicios objeto del presente contrato a más tardar el día": "The Service Provider agrees to deliver the finished deliverables no later than",
    "Cláusula Cuarta: Obligaciones de las partes": "Section 4: Mutual Obligations",

    # Generador de Cotizaciones
    "Datos de la Cotización": "Estimate & Quote Specifications",
    "de la Empresa Emisora": "Issuing Business",
    "del Cliente": "Client Details",
    "de Cotización": "Quote Reference",
    "de Emisión": "Issue Date",
    "de Vencimiento": "Expiration Date",
    "Condiciones de Pago": "Payment Terms",
    "Ítems / Servicios": "Line Items / Services",
    "Agregar Ítem": "Add Line Item",
    "Aplicar Detracción": "Apply Retainage / Withholding",
    "Plantilla de PDF": "PDF Template",
    "COTIZACIÓN": "PRICE ESTIMATE",
    "Emisión:": "Issued:",
    "Sin ítems registrados": "No line items added yet",
    "Cotización generada electrónicamente.": "Commercial estimate generated electronically.",
    "Historial de Cotizaciones": "Quote History",
    "Aún no ha generado cotizaciones. Las que generes aparecerán aquí.": "No quotes generated yet. Generated quotes will appear here.",
    "Tus clientes, catálogo e historial se guardan localmente en este navegador. Exporta una copia para no perderlos si borras el caché.": "Your clients, item catalog, and history are stored locally in this browser. Export a JSON backup to protect against browser cache clearing.",

    # Paletas Corporativas
    "Diseño corporativo": "Corporate Color System",
    "Elige un color base o extráelo de una imagen, ajusta la armonía, simula accesibilidad y genera modo claro/oscuro automáticamente.": "Pick a base color or extract from an image, tune harmony angles, test accessibility contrast, and generate light/dark modes automatically.",
    "Base de color": "Base Color",
    "Generador de paleta": "Palette Generator",
    "Selecciona tu color base y ajusta el ángulo de armonía para pasar de análogos a tríada o tétrada.": "Select your primary base color and adjust harmony angle from analogous to triadic or tetradic.",
    "Ángulo de armonía": "Harmony Angle",
    "Análogos · recálculo en tiempo real": "Analogous · Real-time computation",
    "Análogos · 30 °": "Analogous · 30°",
    "Tétrada · 90 °": "Tetradic · 90°",
    "Tríada · 120 °": "Triadic · 120°",
    "Extraer paleta de una imagen": "Extract Palette from Image",
    "Analizamos los píxeles con K-means para obtener los 5 colores dominantes.": "K-means color clustering extracts the top 5 dominant brand hues.",
    "Sube o arrastra una imagen": "Upload or drag an image here",
    "Los colores dominantes aparecerán aquí.": "Dominant extracted colors will appear here.",
    "Simula deficiencias de visión de color y valida el contraste WCAG.": "Simulate color vision deficiencies and validate WCAG contrast ratios.",
    "Simulador de visión": "Vision Deficiency Simulator",
    "Visión normal": "Trichromacy (Normal Vision)",
    "Deuteranomalía": "Deuteranomaly",
    "Cómo percibiría tu paleta una persona con visión normal.": "How a person with normal color vision perceives your palette.",
    "Contraste WCAG · base de color": "WCAG Contrast · Base Color",
    "ratio de contraste": "contrast ratio",
    "Matriz de contraste cruzado": "Cross-Contrast Matrix",

    # Políticas de Devolución
    "Políticas de devolución": "Return & Refund Policies",
    "claras en segundos": "in Seconds",
    "Redacta textos profesionales sobre garantías y reembolsos adaptados a lo que vendes. Personaliza, previsualiza y exporta.": "Draft clear, professional refund and warranty statements tailored to your products. Customize, preview, and export.",
    "01 — ¿Qué vendes?": "01 — What do you sell?",
    "El texto generado es orientativo. Recomendamos revisarlo con un asesor legal antes de publicarlo.": "Generated policy provides commercial guidance. Have your document reviewed by qualified legal counsel.",

    # Términos y Políticas
    "Privacidad, Términos, Cookies y Aviso Legal en minutos": "Privacy Policy, Terms of Service & Cookie Notices in Minutes",
    "Genera documentos legales básicos para tu web corporativa o tienda online, listos para copiar y publicar.": "Generate foundational website legal policies for corporate websites or ecommerce stores, ready to publish.",
    "Datos de tu empresa": "Company Details",
    "Empezamos por lo básico de tu negocio.": "Start with core company information.",
    "Identificación fiscal": "Tax ID / Business Registration (EIN / ABN)",
    "Tipo de sitio web": "Website Category",
    "Preview en vivo": "Live Policy Preview",
    "Última actualización: 25 de julio de 2026": "Last updated: July 25, 2026",
    "En [Nombre de la Empresa] valoramos y respetamos tu privacidad.": "At [Company Name], we respect and protect your privacy.",
    "1. Responsable del Tratamiento": "1. Data Controller",
    "Podemos recopilar y tratar los siguientes tipos de información personal:": "We may collect and process the following categories of personal data:",
    "Datos de contacto: correo electrónico y número de teléfono.": "Contact information: email address and telephone numbers.",
    "Datos de navegación: dirección IP, tipo de dispositivo y páginas visitadas.": "Technical usage data: IP addresses, browser specifications, and visited pages.",
    "3. Uso de Cookies": "3. Cookie Tracking & Analytics",
    "4. Finalidad del Tratamiento": "4. Purposes of Processing",
    "Mantener la comunicación con los usuarios.": "Maintain direct customer support and communications.",
    "Cumplir con las obligaciones legales aplicables.": "Comply with mandatory statutory obligations.",
    "6. Conservación y Cesión de Datos": "6. Data Retention & Third-Party Disclosure",
    "7. Derechos del Usuario": "7. Your Privacy Rights",
    "8. Usuarios del Espacio Económico Europeo (RGPD)": "8. European Union & GDPR Provisions",

    # Objeciones
    "Los mejores scripts para": "High-Converting Scripts to",
    "manejar cualquier objeción.": "Handle Any Sales Objection.",
    "Encuentra qué decir y por qué funciona, practica el tono en voz alta, recupera el árbol de decisión y presenta sin distracciones con el Zen Mode.": "Learn what to say and why it works, practice delivery aloud, navigate objection trees, and train without distraction in Zen Mode.",
    "Prima de guión. Regístrate gratis para desbloquear toda la biblioteca.": "Pro Script. Full library available.",
    "Cliente Escéptico": "Skeptical Buyer",
    "Anclaje de la mejor opción": "Best Option Anchoring",
    "Tienes razón en que no es la opción más barata; es la que menos veces vas a tener que volver a comprar. Lo barato sale caro dos veces. ¿Prefieres pagar una vez bien o varias veces mal?": '"You\'re right that this isn\'t the cheapest option on the market; it\'s the one you\'ll never have to replace. Cheap solutions get expensive fast. Would you rather invest properly once or pay repeatedly for fixes?"',
    "El anclaje contrasta el dolor de repetir la compra contra el precio actual. Funciona con perfiles impulsivos que deciden por sensación de acierto.": "Anchoring contrasts the recurring pain of failed purchases against upfront cost. Works effectively with buyers seeking long-term reliability.",
    "Cliente Impulsivo": "Impulsive Buyer",
    "De primera calidad": "Premium Quality",
    "Déjame pensarlo": '"I need to think about it"',
    "Concretar el pensamiento": "Uncovering Hidden Doubts",
    "Claro, es una buena decisión pensarla. Solo para ayudarte a pensar mejor: ¿qué es exactamente lo que necesitas resolver en tu cabeza para tomar la decisión? Así te doy justo esa información y no te hago perder tiempo.": '"Of course, taking time to think is a smart move. Just so I can help: what specific factor is still weighing on your mind? That way I can provide that exact detail right now so you don\'t waste time researching."',
    '"Déjame pensarlo" suele ocultar una duda concreta. Al pedir el criterio de decisión, transforma una evasiva vaga en un punto accionable.': '"I need to think about it" usually masks a specific unspoken question. Asking directly turns a polite stall into an actionable conversation.',
    "Cliente ocupado": "Busy Executive",
    "El cierre del pro y contra": "Pros & Cons Reality Check",
    "Perfecto. Para que tu análisis sea completo, hagámoslo juntos 30 segundos: en la columna de a favor tienes X, Y y Z. ¿Qué pondrías tú en la columna de en contra? Trabajemos esa parte.": '"Understood. To help with your analysis, let\'s take 30 seconds together: on the plus side, we have X, Y, and Z. What would you place on the hesitation side? Let\'s address that specific part."',
    "Costo de posponer": "Cost of Inaction",
    "Me parece bien. Solo ten en cuenta una cosa: pensarlo no es gratis. Mientras decide, el problema sigue ahí. ¿Qué tendría que pasar para que valga la pena empezar hoy en lugar de dentro de un mes?": '"I respect that. Just keep one thing in mind: delaying isn\'t cost-free. While we wait, that operational leak continues. What would need to happen today to make starting now worthwhile?"',

    # Inventario
    "Controla existencias, reposición y compras sin depender de un servidor.": "Track product inventory, reorders, and supplier purchase orders with 100% browser privacy.",
    "Valor de stock": "Total Inventory Value",
    "al costo": "at cost",
    "Bajo mínimo": "Low Stock Alerts",
    "requieren reposición": "require immediate reorder",
    "contactos de compra": "active suppliers",
    "Registrar compra de reposición": "Log Stock Replenishment Order",
    "Registra salidas o elimina productos desde la tabla.": "Record outgoing stock shipments or remove discontinued items from the inventory table.",

    # Matriz Contenidos
    "Salud semanal del contenido": "Weekly Content Cadence & Health",
    "Post estático": "Static Image Post",
    "Artículo": "Long-form Article / Blog",
    "Balance por plataforma": "Platform Distribution Balance",
    "Reel: 3 consejos de productividad": "Reel: 3 SMB Productivity Tips",
    "Artículo: tendencias del sector": "Article: Industry Growth Trends",
    "Video corto detrás de cámaras": "Short Video: Behind the Scenes",
    "Suelta una tarjeta aquí": "Drop content card here",

    # TCO
    "TCO Multi-Nodo · Físico vs. Cloud · Análisis de Sensibilidad": "Multi-Node TCO Simulator · On-Premise vs Cloud · Sensitivity Analysis",
    "TCO Físico a 3 Years": "3-Year On-Premise TCO",
    "Opción más económica:": "Most Economical Choice:",
    "Recomendación generada a partir del análisis heurístico": "Heuristic Recommendation Engine",
    "Clúster Físico": "On-Premise Physical Cluster",
    "Energía / mes": "Power & Cooling / mo",
    "Mantenimiento / año": "Maintenance & Support / yr",
    "Licencias / año": "Software Licenses / yr",
    "Tiempo de inactividad / mes": "Unplanned Downtime Cost / mo",
    "Valor de Rescate": "Salvage Residual Value",
    "Clúster Cloud": "Cloud Infrastructure Deployment",
    "Suscripción / mes": "Monthly Cloud Subscription",
    "Análisis de Sensibilidad · Crecimiento del Cloud": "Sensitivity Analysis · Cloud Usage Growth",
    "Tasa anual aplicada al Mes 13 y Mes 25 por escenario": "Annual growth rate applied at Month 13 and Month 25 per scenario",
    "Costos simultáneos": "Cumulative Cost Models",
    "Punto de Quiebre (Break-Even)": "Breakeven Inflection Point",
    "El Cloud se mantiene más económico durante los 36 meses.": "Cloud remains more economical across the entire 36-month projection.",
    "Costo Acumulado del Clúster por Mes": "Cumulative Cluster Cost by Month",
    "Análisis de Sensibilidad de la Nube": "Cloud Sensitivity Analysis",
    "Impacto del crecimiento de uso: Optimista · Realista · Pesimista": "Growth Scenarios: Conservative · Moderate · Aggressive",
    "TCO Cloud a 3 años": "3-Year Cloud TCO",
    "Ahorro vs. Físico:": "Savings vs On-Premise:",
    "Sin cruce en 36 meses": "No breakeven crossover within 36 months",

    # Tareas y Proyectos
    "Convierte compromisos comerciales en trabajo ejecutable y medible.": "Turn client commitments into actionable, measurable deliverables.",
    "pendientes de ejecución": "tasks pending completion",
    "Cliente / área": "Client / Department",
    "Tablero de ejecución": "Operational Task Board",
    "Filtra por proyecto y actualiza el estado directamente.": "Filter by project and drag cards across Kanban columns."
}

# Mapping between Spanish slug and English slug
SLUG_MAP = {
    "analizador-titulares.html": "headline-analyzer.html",
    "auditor-seo-basico.html": "basic-on-page-seo-auditor.html",
    "calculadora-descuentos-promociones.html": "discount-promotions-calculator.html",
    "calculadora-flete-envio-local.html": "local-shipping-calculator.html",
    "calculadora-precios-venta-igv.html": "sales-pricing-tax-calculator.html",
    "calculadora-prestamos-amortizaciones.html": "loan-amortization-calculator.html",
    "calculadora-sobrecostos-laborales.html": "labor-cost-payroll-burden-calculator.html",
    "comparador-campanas-avanzado.html": "advanced-campaign-comparator.html",
    "consola-campanas.html": "campaign-utm-console.html",
    "conversor-optimizador-imagenes.html": "image-converter-optimizer.html",
    "creador-facturas-proforma.html": "proforma-invoice-generator.html",
    "crm-pymes.html": "smb-crm.html",
    "firma-correo-html.html": "html-email-signature.html",
    "flujo-caja-pymes.html": "cash-flow-tracker.html",
    "generador-codigos-qr.html": "qr-code-generator.html",
    "generador-contrasenas-pymes.html": "smb-password-generator.html",
    "generador-contratos-servicios.html": "service-contracts-generator.html",
    "generador-cotizaciones.html": "quote-estimate-generator.html",
    "generador-paletas-corporativas.html": "brand-palette-generator.html",
    "generador-politicas-devolucion.html": "return-policy-generator.html",
    "generador-politicas-terminos.html": "terms-privacy-generator.html",
    "guiones-manejo-objeciones.html": "objection-handling-scripts.html",
    "inventario-compras-pymes.html": "inventory-purchasing.html",
    "organizador-matriz-contenidos.html": "content-matrix-planner.html",
    "simulador-tco-fisico-nube.html": "cloud-vs-onprem-tco-simulator.html",
    "tareas-proyectos-pymes.html": "tasks-projects-tracker.html"
}

count_updated = 0
for es_slug, en_slug in SLUG_MAP.items():
    es_path = EN_DIR / es_slug
    if not es_path.exists():
        continue
    content = es_path.read_text(encoding="utf-8", errors="ignore")

    # Apply all dictionary replacements
    for src, dst in REPLACEMENTS.items():
        if src in content:
            content = content.replace(src, dst)

    # Clean up any lingering garbled characters
    content = content.replace("Ã¡", "á").replace("Ã©", "é").replace("Ã­", "í").replace("Ã³", "ó").replace("Ãº", "ú").replace("Ã±", "ñ")

    # Ensure lang="en"
    content = re.sub(r'<html[^>]*lang="[^"]*"', '<html lang="en"', content)

    # Ensure relative paths for css/js/assets
    content = re.sub(r'href="\./css/', 'href="../css/', content)
    content = re.sub(r'src="\./js/', 'src="../js/', content)
    content = re.sub(r'src="\./assets/', 'src="../assets/', content)
    content = re.sub(r'href="\./assets/', 'href="../assets/', content)

    # Save to both Spanish slug and English slug in en/
    es_path.write_text(content, encoding="utf-8")
    (EN_DIR / en_slug).write_text(content, encoding="utf-8")
    count_updated += 2

print(f"Deep translation v2 applied across {count_updated} files in en/!")
